[jobs.default]
command = ["cargo", "check", "--workspace"]
need_stdout = false
watch = ["crates/"]

[jobs.kernelle]
command = ["cargo", "install", "--path", "crates/kernelle", "--force"]
need_stdout = false
watch = ["crates/kernelle/"]

[jobs.violet]
command = ["cargo", "install", "--path", "crates/violet", "--force"]
need_stdout = false
watch = ["crates/violet/"]

[jobs.blizz]
command = ["cargo", "install", "--path", "crates/blizz", "--force"]
need_stdout = false
watch = ["crates/blizz/"]

[jobs.all]
command = ["cargo", "build", "--workspace"]
need_stdout = false
watch = ["crates/"]

[jobs.test]
command = ["cargo", "test", "--workspace"]
need_stdout = true
watch = ["crates/"]

[jobs.clippy]
command = ["cargo", "clippy", "--workspace", "--", "-D", "warnings"]
need_stdout = false
watch = ["crates/"] 
