[workspace]
resolver = "2"
members = [
    "crates/adam",
    "crates/bentley", 
    "crates/blizz",
    "crates/jerrod",
    "crates/violet"
]

[workspace.package]
edition = "2021"
authors = ["Jeff <jeffhilton.ctr@gmail.com>"]
license = "Private"
repository = "https://github.com/jhilton/bentley"

[workspace.dependencies]
# Internal crates
bentley = { path = "crates/bentley" }

# GitLab API
gitlab = "0.1800"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }

# CLI
clap = { version = "4.5", features = ["derive", "env"] }

# Async runtime
tokio = { version = "1.38", features = ["full"] }

# JSON handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Date/time handling
chrono = { version = "0.4", features = ["serde"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# File system and paths
dirs = "5.0"

# Terminal output
colored = "2.1"
console = "0.15"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# HTTP client features
url = "2.5"

# Testing
tempfile = "3.8"
tokio-test = "0.4" 