[workspace]
resolver = "2"
members = [
    "crates/adam",
    "crates/bentley", 
    "crates/blizz",
    "crates/jerrod",
    "crates/kernelle",
    "crates/sentinel",
    "crates/violet"
]

[workspace.package]
version = "0.2.7"
edition = "2021"
authors = ["Voxel <travelsizedlions@gmail.com>"]
license = "Private"
repository = "https://github.com/TravelsizedLions/kernelle"

[workspace.dependencies]
bentley = { path = "crates/bentley" }

gitlab = "0.1800"
reqwest = { version = "0.12.20", features = ["json", "rustls-tls"] }

clap = { version = "4.5", features = ["derive", "env"] }

tokio = { version = "1.38", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

chrono = { version = "0.4", features = ["serde"] }

anyhow = "1.0"
thiserror = "1.0"

dirs = "6.0"

colored = "3.0"
console = "0.16"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

url = "2.5"

tempfile = "3.8"
tokio-test = "0.4" 
