[tarpaulin]
coverage-reports = ["Html", "Lcov", "Json"]
output-dir = "target/coverage/"

fail-under = 40.0  
ignore-panics = true

skip-clean = false
count = true
line = true
branch = true
forward = true

exclude = [
  "*/tests/*",
  "*/examples/*", 
  "*/target/*",
  # Exclude main.rs files since they're just CLI entry points
  "*/src/main.rs",
  # Auth module uses external credentials - hard to test
  "*/auth.rs",
]

timeout = "120s"

run-types = ["Tests"]

all-features = true
workspace = true

engine = "Llvm" 
