[package]
name = "bentley"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Theatrical logging and output formatting library - the town crier of Kernelle"

[lib]
name = "bentley"
path = "src/lib.rs"

[dependencies]
# Terminal output
colored.workspace = true
console.workspace = true

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true

# Date/time handling
chrono.workspace = true

# Error handling
anyhow.workspace = true
thiserror.workspace = true

# JSON handling
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true 