[package]
name = "violet"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Code complexity analysis and style enforcement tool"

[[bin]]
name = "violet"
path = "src/main.rs"

[dependencies]
clap.workspace = true

anyhow.workspace = true
thiserror.workspace = true

dirs.workspace = true

colored.workspace = true
console.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

serde.workspace = true
serde_json.workspace = true

# Tree-sitter parsing
tree-sitter = "0.25"
tree-sitter-javascript = "0.23"
tree-sitter-typescript = "0.23"
tree-sitter-python = "0.23"
tree-sitter-rust = "0.24"
tree-sitter-bash = "0.25"
tree-sitter-go = "0.23"
tree-sitter-ruby = "0.23"
tree-sitter-php = "0.23"

# File operations and path handling
walkdir = "2.4"
globset = "0.4"
[dev-dependencies]
tempfile.workspace = true 