name: Validate Development Branch

on:
  push:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage-linux:
    name: Coverage (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kernelle Dependencies
        uses: ./.github/actions/setup-kernelle

      - name: Test with Coverage and Update Badge
        uses: ./.github/actions/test-with-coverage
        with:
          generate-coverage: 'true'
          upload-coverage: 'true'
          update-badge: 'true'
          coverage-artifact-name: 'stable-coverage'
