name: Validate Development Branch

on:
  push:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage-linux:
    name: Validate and Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kernelle Dependencies
        uses: ./.github/actions/setup-kernelle

      - name: Test with Coverage and Update Badge
        uses: ./.github/actions/test
        with:
          report-coverage: 'true'
          update-badge: 'true'

      - name: Bump and Tag Version
        run: |
          .github/run/bump-version.sh
          .github/run/tag-version.sh
        
      - name: Push Changes
        run: |
          git push origin dev
          # Push the newly created tag (if any) to trigger release workflow
          NEW_TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
          if [ ! -z "$NEW_TAG" ]; then
            echo "🏷️ Pushing tag: $NEW_TAG"
            git push origin "$NEW_TAG"
          else
            echo "ℹ️ No tag found on current commit"
          fi
