name: Linux

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kernelle Dependencies
        uses: ./.github/actions/setup-kernelle

      - name: Build Project
        run: kernelle do ci:build

      - name: Generate Coverage Report
        run: kernelle do coverage

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: linux-coverage
          path: coverage/
          retention-days: 30
      
      - name: Generate coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura.xml
          format: markdown
          output: both
          indicators: true
          badge: true
          


      - name: Post coverage as PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
          
      - name: Update coverage badge in README
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: |
          # Extract the badge line (first line) from the coverage results
          NEW_BADGE=$(head -n 1 code-coverage-results.md)
          
          # Replace the coverage badge line in README.md
          sed -i "s|^!\[Code Coverage\](https://img\.shields\.io/badge/.*|$NEW_BADGE|" README.md
          
          # Check if there were changes
          if git diff --quiet README.md; then
            echo "No changes to README.md"
          else
            echo "Coverage badge updated in README.md"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "Update coverage badge [skip ci]"
            git push
          fi
