name: Linux

on:
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kernelle Dependencies
        uses: ./.github/actions/setup-kernelle

      - name: Test with Coverage
        uses: ./.github/actions/test
        with:
          report-coverage: 'true'
          post-pr-comment: 'true'
          coverage-artifact-name: 'pr-coverage'
