name: Linux

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kernelle & Global Dependencies
        uses: ./.github/actions/setup-kernelle

      - name: Generate Coverage Report
        run: kernelle do coverage

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: linux-coverage
          path: coverage/
          retention-days: 30
      
      - name: Generate coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura.xml
          format: markdown
          output: both
          indicators: true
          badge: true

      - name: Post coverage as PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
          
      - name: Update coverage badge in README
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: .github/run/create-coverage-badge.sh
          
