name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get tag version
        id: version
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Verify version matches Cargo.toml
        run: |
          ./.github/workflows/scripts/verify-version.sh "${{ steps.version.outputs.version }}"
      
      - name: Run tests
        run: |
          cargo test --workspace
      
      - name: Create source archive
        run: |
          ./.github/workflows/scripts/create-source-archive.sh "${{ steps.version.outputs.tag }}"
      
      - name: Generate release notes
        run: |
          ./.github/workflows/scripts/generate-release-notes.sh \
            "${{ steps.version.outputs.tag }}" \
            "${{ steps.version.outputs.version }}"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Kernelle ${{ steps.version.outputs.version }}
          body_path: release_notes.md
          files: |
            kernelle-${{ steps.version.outputs.tag }}-source.tar.gz
            kernelle-${{ steps.version.outputs.tag }}-source.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 