name: Security Audit

on:
  pull_request:
  push:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: security-${{ hashFiles('**/Cargo.lock') }}
          cache-on-failure: true

      - name: Install cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
        env:
          # Enable explicit caching for installed tools
          CARGO_INSTALL_ROOT: ~/.cargo

      - name: Run security audit
        run: |
          echo "🔒 Running security audit..."
          cargo audit

      - name: Check for known vulnerabilities
        run: |
          echo "🛡️ Scanning for known vulnerabilities..."
          cargo audit --deny warnings

      - name: Security success
        run: echo "🔐 Security audit passed! No vulnerabilities detected!" 