name: windows

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always
 
jobs:
  test-windows:
    name: Test (Windows)
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip validation]')"

    steps:
      - name: Skip
        run: echo "Unfortunate, but Windows CI testing is so slow that it's not worth the time at the moment."
